version: '2'
services:
  web:
    build: .
    command: php -S 0.0.0.0:8001 -t /code/wordpress/
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - .:/code
  db:
    image: orchardup/mysql
    environment:
      MYSQL_DATABASE: wordpress
